spring.application.name=auth-service-api
server.port=9092

# Database configuration
spring.datasource.url=jdbc:mysql://localhost:3306/ec7205_eventHub_auth?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=1234
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.data.jdbc.dialect=mysql
spring.jpa.generate-ddl=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect


eureka.client.serviceUrl.defaultZone=http://localhost:8761/eureka/

#================keycloak configurations
spring.security.oauth2.resourceserver.jwt.token-uri=http://localhost:8080/realms/cpd/protocol/openid-connect/token
spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:8080/realms/cpd
public.key.string=MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAyR+oTOar0NiIYa2jFF0UQ10tWEhCk6M3v5r2hR0YUaQFqQVIvPJ8QCL1SQSBCxSBgWF2cjKS80gnOmyWhG21xF0rIGuehDa4YxFG1zV1ql8y30BleypHD/LpxZhtzcRqPP+eSWgkRC9yv/I3f9bTKR/2ArFgPkyxIJbhV4xH+RlRehb5gAGZz9XIG+6uO4yP0sZZ6tHZxcmggmNGm6CmqGOAnj7867uD4t1YQs7hvnTs6uize7DQW5+C79owcHIsTDzqP/jUs3MJhl2+AXEeuI978/RpbWdIqvavwg1PUC/UmQYX5HpVgGY0s1ocJxilMzDs5QmtvQ2VA2XcTKPHNwIDAQAB

keycloak.config.realm=cpd
keycloak.config.server-url=http://localhost:8080/
keycloak.config.client-id=cpd-client
keycloak.config.grant-type=password
keycloak.config.name=amirumithsara1234@gmail.com
keycloak.config.secret=uAv7VoL1san7BuR7L1V8WlZ439YrhgJb
keycloak.config.password=1234


#======================Sengrid configurations
emailKey=SG.AXthuauYRo-rdlcX53_HUw.geSBgJUMdDdEzeBYqc0W6DNs3kY0jB89fNvMXzASHs
#E
fromEmail=hasikasandaruwan.info@gmail.com
replyEmail=hasikasandaruwan.info@gmail.com

accessKey=AJHSHDJSHKDJHSKHKHDK
secret=DSHjdkfhSJDHKsfkjj
bucketName=test-bucket-name
region=ap-south-1

#=======================AWS S3 bucket configuration
accessKey=AKIAQEIP3PZKVZV6E37V
secret=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
bucketName=cpd-hotel
region=us-east-1